### ISSUE TITLE
confundir la ética con el tocino

### ISSUE THREAD

**Issue by dazer** [duhow/Trainer-Conduct-Code#1]
radares: "el orígen de datos no es ético"
Si se describe como excepción aceptable, ha de ser necesariamente ético. La *justificación* de romper una regla ha de ser un razonamiento convincente que lleve a pensar que es justo y, por tanto, ético.
Normalmente se argumenta que es justo usar un radar en tanto en cuanto el juego no ofrece uno. Eso es esencialmente lo que encapsula la famosa carta del creador de Pokevision cuando cerró.
Faltando tal justificación, la excepción es esencialmente: esto está mal pero nos la suda mil.

Por otro lado el lenguaje utilizado lleva a equívoco.
-a pesar de que no perjudican directamente a los usuarios.
-siempre y cuando no afecten a la jugabilidad de los usuarios.
Los radares puede que no perjudiquen *directamente* a los usuarios, pero sí afectan a la jugabilidad de manera indirecta siempre: es carga nada despreciable en su servidor.

Hablando de permisibilidad, es importante mantener el ámbito de aplicación adecuado.
-"Avisar del avistamiento del Pokémon no es ilegal"
Sólo faltaba: hacer trampas al parchis tampoco es ilegal. Estamos hablando de prescripciones sociales, no de la legislación aplicable.

Finalmente: no está nisiquiera claro que sea trampa.
Ni el TOS ni las reglas del entrenador prohiben explícitamente el uso de radares. Si pensamos que usar un radar es "usar software modificado o no oficial", la conclusión lógica es pensar que usar ProfesorOak_bot o el mismo telegram es también "usar software modificado o no oficial".

Como medida transitoria sugiero directamente borrar la sección. Si realmente se necesita una aclaración, este es un buen foro para discutir qué debería incluir.

**Comment by duhow** [comment]
Vamos a dejarlo en que no voy a cambiar el pensamiento de la gente y decir que se olviden de radares, porque van a seguir créandolos y usándolos.

Estamos totalmente de acuerdo en el tema de la carga de los servidores de Niantic, aunque tampoco es que estén apretados porque haya 100.000+ cuentas que sólo se utilicen para encontrar Pokémon, y es algo que la propia compañía debe trabajar para impedir de una vez por todas el funcionamiento de dichas cuentas o cómo se mueven, o bien ofrecer el mismo servicio que pide la gente de forma pública.

Por otra parte, los radares ya de por sí inflingen las **Normas del Entrenador** al *jugar con múltiples cuenta* y *usar herramientas o técnicas para alterar o falsificar la ubicación*, pero afectan a éstas cuentas *vacías*, no a los jugadores. La visualización de la información del radar / mapa no identifica a ninguna persona o cuenta, por lo que los usuarios no corren ningún riesgo.

Finalmente, no compares al Oak con un radar. Oak es una base de datos **OFFLINE** que recopila información proporcionada por los propios usuarios u otras bases de datos públicas, pero **jamás directamente de Niantic**. Por lo tanto, sigue siendo lo mismo, los usuarios no incumplen ninguna norma por registrarse con el mismo nombre que en Pokémon GO, o por decir su color.
